package com.model;

import jakarta.persistence.*;

/**
 * Represents a building type in the digital twin city planning system.
 * <p>
 * This entity stores configuration data for different types of buildings and land use,
 * including their visual appearance (color), economic properties (cost and income),
 * and social impact (people capacity and livability score).
 * </p>
 * <p>
 * Building types are referenced by polygons in the 3D city model to determine
 * how buildings are rendered and how they contribute to city goals and metrics.
 * </p>
 *
 * @author Digital Twin Development Team
 * @version 1.0
 * @since 1.0
 */
@Entity
@Table(name = "building_types")
public class BuildingType {
    
    /**
     * Unique identifier for this building type in the database.
     * Auto-generated by the persistence layer.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Unique type identifier used to reference this building type.
     * Examples: "commercial building", "nature", "residential", etc.
     */
    @Column(nullable = false, unique = true)
    private String typeId;
    
    /**
     * Color representation in hexadecimal format for visual rendering.
     * Format: "#RRGGBB" (e.g., "#039BE5" for blue).
     */
    @Column(nullable = false)
    private String colorHex;
    
    /**
     * Construction cost in euros.
     * Multiplied by either volume or area based on {@link #calculationBase}.
     */
    @Column(nullable = false)
    private Double cost;
    
    /**
     * Financial income as a percentage of cost per unit.
     * Used to calculate economic returns from this building type.
     */
    @Column(nullable = false)
    private Double income;
    
    /**
     * Capacity for people (residents or workers) per unit.
     * Used to calculate total population impact in city planning.
     */
    @Column(nullable = false)
    private Double people;
    
    /**
     * Livability score on a scale of 1 to 10.
     * Represents quality of life contribution of this building type.
     */
    @Column(nullable = false)
    private Double livability;
    
    /**
     * Basis for cost calculations: "volume" or "area".
     * Determines whether cost is multiplied by cubic meters or square meters.
     * Default value is "volume".
     */
    @Column(nullable = false)
    private String calculationBase = "volume";
    
    /**
     * Default no-argument constructor required by JPA.
     */
    public BuildingType() {
    }
    
    /**
     * Constructs a BuildingType with volume-based cost calculation.
     * The calculationBase is automatically set to "volume".
     *
     * @param typeId the unique type identifier
     * @param colorHex the color in hexadecimal format
     * @param cost the construction cost in euros per cubic meter
     * @param income the income as percentage of cost
     * @param people the capacity for people per unit
     * @param livability the livability score (1-10)
     */
    public BuildingType(String typeId, String colorHex, Double cost, Double income, Double people, Double livability) {
        this.typeId = typeId;
        this.colorHex = colorHex;
        this.cost = cost;
        this.income = income;
        this.people = people;
        this.livability = livability;
        this.calculationBase = "volume";
    }
    
    /**
     * Constructs a BuildingType with specified calculation base.
     *
     * @param typeId the unique type identifier
     * @param colorHex the color in hexadecimal format
     * @param cost the construction cost in euros (per volume or area)
     * @param income the income as percentage of cost
     * @param people the capacity for people per unit
     * @param livability the livability score (1-10)
     * @param calculationBase the basis for cost calculation ("volume" or "area")
     */
    public BuildingType(String typeId, String colorHex, Double cost, Double income, Double people, Double livability, String calculationBase) {
        this.typeId = typeId;
        this.colorHex = colorHex;
        this.cost = cost;
        this.income = income;
        this.people = people;
        this.livability = livability;
        this.calculationBase = calculationBase;
    }
    
    /**
     * Gets the unique database identifier.
     *
     * @return the id
     */
    public Long getId() {
        return id;
    }
    
    /**
     * Sets the unique database identifier.
     *
     * @param id the id to set
     */
    public void setId(Long id) {
        this.id = id;
    }
    
    /**
     * Gets the unique type identifier.
     *
     * @return the type identifier
     */
    public String getTypeId() {
        return typeId;
    }
    
    /**
     * Sets the unique type identifier.
     *
     * @param typeId the type identifier to set
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }
    
    /**
     * Gets the color in hexadecimal format.
     *
     * @return the color hex string
     */
    public String getColorHex() {
        return colorHex;
    }
    
    /**
     * Sets the color in hexadecimal format.
     *
     * @param colorHex the color hex string to set
     */
    public void setColorHex(String colorHex) {
        this.colorHex = colorHex;
    }
    
    /**
     * Gets the construction cost.
     *
     * @return the cost in euros
     */
    public Double getCost() {
        return cost;
    }
    
    /**
     * Sets the construction cost.
     *
     * @param cost the cost in euros to set
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }
    
    /**
     * Gets the income percentage.
     *
     * @return the income as percentage of cost
     */
    public Double getIncome() {
        return income;
    }
    
    /**
     * Sets the income percentage.
     *
     * @param income the income as percentage of cost to set
     */
    public void setIncome(Double income) {
        this.income = income;
    }
    
    /**
     * Gets the people capacity.
     *
     * @return the number of people per unit
     */
    public Double getPeople() {
        return people;
    }
    
    /**
     * Sets the people capacity.
     *
     * @param people the number of people per unit to set
     */
    public void setPeople(Double people) {
        this.people = people;
    }
    
    /**
     * Gets the livability score.
     *
     * @return the livability score (1-10)
     */
    public Double getLivability() {
        return livability;
    }
    
    /**
     * Sets the livability score.
     *
     * @param livability the livability score (1-10) to set
     */
    public void setLivability(Double livability) {
        this.livability = livability;
    }
    
    /**
     * Gets the calculation base.
     *
     * @return the calculation base ("volume" or "area")
     */
    public String getCalculationBase() {
        return calculationBase;
    }
    
    /**
     * Sets the calculation base.
     *
     * @param calculationBase the calculation base to set ("volume" or "area")
     */
    public void setCalculationBase(String calculationBase) {
        this.calculationBase = calculationBase;
    }
}
