package com.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;

/**
 * Represents a geographic coordinate point in the digital twin system.
 * <p>
 * Coordinates define the vertices of polygons in the 3D city model.
 * Each coordinate has longitude and latitude values and belongs to a parent polygon.
 * Multiple coordinates form the boundary of a polygon representing a building or land area.
 * </p>
 * <p>
 * The relationship with {@link Polygon} is bidirectional, with the coordinate being
 * the child entity in a many-to-one relationship.
 * </p>
 *
 * @author Digital Twin Development Team
 * @version 1.0
 * @since 1.0
 * @see Polygon
 */
@Entity
@Table(name = "coordinates")
public class Coordinate {
    
    /**
     * Unique identifier for this coordinate in the database.
     * Auto-generated by the persistence layer.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Longitude value in decimal degrees.
     * Represents the east-west position of the coordinate.
     */
    @Column(nullable = false)
    private Double longitude;
    
    /**
     * Latitude value in decimal degrees.
     * Represents the north-south position of the coordinate.
     */
    @Column(nullable = false)
    private Double latitude;
    
    /**
     * Reference to the parent polygon that owns this coordinate.
     * Uses JsonBackReference to prevent infinite recursion during JSON serialization.
     */
    @ManyToOne
    @JoinColumn(name = "polygon_id")
    @JsonBackReference
    private Polygon polygon;

    /**
     * Default no-argument constructor required by JPA.
     */
    public Coordinate() {}

    /**
     * Constructs a Coordinate with specified longitude and latitude.
     *
     * @param longitude the longitude in decimal degrees
     * @param latitude the latitude in decimal degrees
     */
    public Coordinate(Double longitude, Double latitude) {
        this.longitude = longitude;
        this.latitude = latitude;
    }

    /**
     * Gets the unique database identifier.
     *
     * @return the id
     */
    public Long getId() { 
        return id; 
    }
    
    /**
     * Sets the unique database identifier.
     *
     * @param id the id to set
     */
    public void setId(Long id) { 
        this.id = id; 
    }
    
    /**
     * Gets the longitude value.
     *
     * @return the longitude in decimal degrees
     */
    public Double getLongitude() { 
        return longitude; 
    }
    
    /**
     * Sets the longitude value.
     *
     * @param longitude the longitude in decimal degrees to set
     */
    public void setLongitude(Double longitude) { 
        this.longitude = longitude; 
    }

    /**
     * Gets the latitude value.
     *
     * @return the latitude in decimal degrees
     */
    public Double getLatitude() { 
        return latitude; 
    }
    
    /**
     * Sets the latitude value.
     *
     * @param latitude the latitude in decimal degrees to set
     */
    public void setLatitude(Double latitude) { 
        this.latitude = latitude; 
    }
    
    /**
     * Gets the parent polygon.
     *
     * @return the polygon that owns this coordinate
     */
    public Polygon getPolygon() { 
        return polygon; 
    }
    
    /**
     * Sets the parent polygon.
     *
     * @param polygon the polygon to set as owner
     */
    public void setPolygon(Polygon polygon) { 
        this.polygon = polygon; 
    }
}