// Polygon.java
package com.model;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a polygon-based structure in the digital twin city planning system.
 * <p>
 * Polygons are the primary building blocks of the 3D city model, representing buildings,
 * land areas, and other structures. Each polygon is defined by a list of {@link Coordinate}
 * vertices that form its boundary, along with properties like height and building type.
 * </p>
 * <p>
 * The polygon can have a {@link BuildingType} association to determine its visual appearance,
 * economic properties, and contribution to city goals. Special features include the ability
 * to mark a polygon as having "nature on top" (green roof) for environmental calculations.
 * </p>
 *
 * @author Digital Twin Development Team
 * @version 1.0
 * @since 1.0
 * @see Coordinate
 * @see BuildingType
 */
@Entity
@Table(name = "polygons")
public class Polygon {
    
    /**
     * Unique identifier for this polygon in the database.
     * Auto-generated by the persistence layer.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * List of coordinates defining the polygon's boundary.
     * Uses JsonManagedReference for proper JSON serialization with bidirectional relationship.
     * Cascade operations ensure coordinates are persisted/deleted with the polygon.
     */
    @OneToMany(mappedBy = "polygon", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @JsonManagedReference
    private List<Coordinate> coordinates = new ArrayList<>();
    
    /**
     * Height of the structure in meters.
     * Determines the vertical extent of the 3D model.
     */
    @Column(nullable = false)
    private Double height;
    
    /**
     * Reference to the building type identifier.
     * Links to BuildingType.typeId (e.g., "commercial building", "nature", "residential").
     */
    @Column(name = "building_type")
    private String buildingType;

    /**
     * User-defined name for this polygon.
     * Optional field for easier identification and management.
     */
    @Column(name = "name")
    private String name;

    /**
     * Indicates whether the polygon has nature on top (green roof).
     * When true, contributes to nature goals but not to occupation calculations.
     */
    @Column(name = "has_nature_on_top")
    private Boolean hasNatureOnTop = false;

    /**
     * Default no-argument constructor required by JPA.
     * Initializes height to 0.0 and hasNatureOnTop to false.
     */
    public Polygon() {
        this.height = 0.0;
        this.hasNatureOnTop = false;
    }

    /**
     * Constructs a Polygon with specified coordinates, height, and building type.
     *
     * @param coordinates the list of coordinates defining the polygon boundary
     * @param height the height in meters
     * @param buildingType the building type identifier
     */
    public Polygon(List<Coordinate> coordinates, Double height, String buildingType) {
        this.coordinates = coordinates;
        this.height = height;
        this.buildingType = buildingType;
    }

    /**
     * Gets the unique database identifier.
     *
     * @return the id
     */
    public Long getId() { 
        return id; 
    }
    
    /**
     * Sets the unique database identifier.
     *
     * @param id the id to set
     */
    public void setId(Long id) { 
        this.id = id; 
    }

    /**
     * Gets the list of coordinates.
     *
     * @return the coordinates defining the polygon boundary
     */
    public List<Coordinate> getCoordinates() { 
        return coordinates; 
    }
    
    /**
     * Sets the list of coordinates and establishes the bidirectional relationship.
     * Each coordinate's polygon reference is automatically set to this polygon.
     *
     * @param coordinates the coordinates to set
     */
    public void setCoordinates(List<Coordinate> coordinates) { 
        this.coordinates = coordinates;
        // Set parent reference for bidirectional relationship
        if (coordinates != null) {
            for (Coordinate coord : coordinates) {
                coord.setPolygon(this);
            }
        }
    }

    /**
     * Gets the height of the structure.
     *
     * @return the height in meters
     */
    public Double getHeight() { 
        return height; 
    }
    
    /**
     * Sets the height of the structure.
     *
     * @param height the height in meters to set
     */
    public void setHeight(Double height) { 
        this.height = height; 
    }

    /**
     * Gets the building type identifier.
     *
     * @return the building type identifier
     */
    public String getBuildingType() { 
        return buildingType; 
    }
    
    /**
     * Sets the building type identifier.
     *
     * @param buildingType the building type identifier to set
     */
    public void setBuildingType(String buildingType) { 
        this.buildingType = buildingType; 
    }

    /**
     * Gets the user-defined name.
     *
     * @return the name of the polygon
     */
    public String getName() { 
        return name; 
    }
    
    /**
     * Sets the user-defined name.
     *
     * @param name the name to set
     */
    public void setName(String name) { 
        this.name = name; 
    }

    /**
     * Gets whether the polygon has nature on top.
     *
     * @return true if the polygon has a green roof, false otherwise
     */
    public Boolean getHasNatureOnTop() { 
        return hasNatureOnTop; 
    }
    
    /**
     * Sets whether the polygon has nature on top.
     *
     * @param hasNatureOnTop true to mark as having a green roof, false otherwise
     */
    public void setHasNatureOnTop(Boolean hasNatureOnTop) { 
        this.hasNatureOnTop = hasNatureOnTop; 
    }

    /**
     * Helper method to add a coordinate to the polygon.
     * Automatically establishes the bidirectional relationship.
     *
     * @param coordinate the coordinate to add
     */
    public void addCoordinate(Coordinate coordinate) {
        coordinates.add(coordinate);
        coordinate.setPolygon(this);
    }
}