package com.dto;

/**
 * Data Transfer Object for polygon data calculations.
 * Contains financial, demographic, and livability metrics for a polygon area.
 */
public class PolygonDataResponse {
    
    /**
     * Total cost in euros for this polygon area.
     */
    private Double cost;
    
    /**
     * Total income in euros generated by this polygon area.
     */
    private Double income;
    
    /**
     * Number of people (residents or workers) or parking spaces (for parking types).
     */
    private Double people;
    
    /**
     * Livability score ranging from 1 to 10, where 10 is highest livability.
     */
    private Double livability;
    
    /**
     * The measurement value (area or volume) used in the calculation.
     */
    private Double measurement;
    
    /**
     * Indicates the basis for calculation: "area" (square meters) or "volume" (cubic meters).
     */
    private String calculationBase;
    
    // Constructors
    public PolygonDataResponse() {
    }
    
    public PolygonDataResponse(Double cost, Double income, Double people, Double livability, 
                               Double measurement, String calculationBase) {
        this.cost = cost;
        this.income = income;
        this.people = people;
        this.livability = livability;
        this.measurement = measurement;
        this.calculationBase = calculationBase;
    }
    
    // Getters and Setters
    public Double getCost() {
        return cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    
    public Double getIncome() {
        return income;
    }
    
    public void setIncome(Double income) {
        this.income = income;
    }
    
    public Double getPeople() {
        return people;
    }
    
    public void setPeople(Double people) {
        this.people = people;
    }
    
    public Double getLivability() {
        return livability;
    }
    
    public void setLivability(Double livability) {
        this.livability = livability;
    }
    
    public Double getMeasurement() {
        return measurement;
    }
    
    public void setMeasurement(Double measurement) {
        this.measurement = measurement;
    }
    
    public String getCalculationBase() {
        return calculationBase;
    }
    
    public void setCalculationBase(String calculationBase) {
        this.calculationBase = calculationBase;
    }
}
